[project]
name = "crafterx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.98.0",
    "pymilvus>=2.5.14",
    "requests>=2.32.4",
    "tqdm>=4.67.1",
]
